CREATE TABLE projects (
    id BIGINT generated BY DEFAULT AS IDENTITY,
    title TEXT NOT NULL,
    owner_email  TEXT NOT NULL UNIQUE,
    CONSTRAINT projects_id_pkey PRIMARY KEY (id)
);

CREATE TABLE services (
    id BIGINT generated BY DEFAULT AS IDENTITY,
    service_title TEXT NOT NULL UNIQUE,
    service_address TEXT NOT NULL UNIQUE,
    service_techuser TEXT NOT NULL UNIQUE,
    service_passwd TEXT NOT NULL UNIQUE,
    CONSTRAINT services_id_pkey PRIMARY KEY (id)
);

CREATE TABLE instances (
 id BIGINT generated BY DEFAULT AS IDENTITY,
 service_id BIGINT NOT NULL,
 instance_name TEXT NOT NULL UNIQUE,
 instance_expire_time TEXT NOT NULL,
 project_id BIGINT NOT NULL,
 CONSTRAINT instances_fk_service_id FOREIGN KEY (service_id) REFERENCES services(id) ON DELETE RESTRICT,
 CONSTRAINT instances_fk_project_id FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE RESTRICT
);
